// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SegmentsColumns holds the columns for the "segments" table.
	SegmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// SegmentsTable holds the schema information for the "segments" table.
	SegmentsTable = &schema.Table{
		Name:       "segments",
		Columns:    SegmentsColumns,
		PrimaryKey: []*schema.Column{SegmentsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserSegmentsColumns holds the columns for the "user_segments" table.
	UserSegmentsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "segment_id", Type: field.TypeInt},
	}
	// UserSegmentsTable holds the schema information for the "user_segments" table.
	UserSegmentsTable = &schema.Table{
		Name:       "user_segments",
		Columns:    UserSegmentsColumns,
		PrimaryKey: []*schema.Column{UserSegmentsColumns[0], UserSegmentsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_segments_user_id",
				Columns:    []*schema.Column{UserSegmentsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_segments_segment_id",
				Columns:    []*schema.Column{UserSegmentsColumns[1]},
				RefColumns: []*schema.Column{SegmentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SegmentsTable,
		UsersTable,
		UserSegmentsTable,
	}
)

func init() {
	UserSegmentsTable.ForeignKeys[0].RefTable = UsersTable
	UserSegmentsTable.ForeignKeys[1].RefTable = SegmentsTable
}
