// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awesomeProject/ent/segment"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Segment is the model entity for the Segment schema.
type Segment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SegmentQuery when eager-loading is set.
	Edges        SegmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SegmentEdges holds the relations/edges for other nodes in the graph.
type SegmentEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e SegmentEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Segment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case segment.FieldID:
			values[i] = new(sql.NullInt64)
		case segment.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Segment fields.
func (s *Segment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case segment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case segment.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Segment.
// This includes values selected through modifiers, order, etc.
func (s *Segment) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Segment entity.
func (s *Segment) QueryUsers() *UserQuery {
	return NewSegmentClient(s.config).QueryUsers(s)
}

// Update returns a builder for updating this Segment.
// Note that you need to call Segment.Unwrap() before calling this method if this Segment
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Segment) Update() *SegmentUpdateOne {
	return NewSegmentClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Segment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Segment) Unwrap() *Segment {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Segment is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Segment) String() string {
	var builder strings.Builder
	builder.WriteString("Segment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Segments is a parsable slice of Segment.
type Segments []*Segment
