// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Segment is the predicate function for segment builders.
type Segment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
